version: '3'

services:
  ids-system:
    build:
      context: .
      dockerfile: Dockerfile.ids
    stdin_open: true
    tty: true
    network_mode: "host"  # Use the host network
    volumes:
      - shared-db:/app/db

  web-server:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5001:5000"
    volumes:
      - shared-db:/app/db
    command: python3 appy.py

  traffic-simulator:
    build:
      context: .
      dockerfile: Dockerfile.tcpreplay
    depends_on:
      - ids-system
    network_mode: "host"  # Use the host network
    volumes:
      - shared-db:/app/db

volumes:
  shared-db:
    driver: local
